export const languages = [{"language":"Afrikaans","text": "Hello Wêreld!"},
    {"language":"Albanian","text": "Përshendetje Botë!"},
    {"language":"Amharic","text": "ሰላም ልዑል!"},
    {"language":"Arabic","text": "مرحبا بالعالم!"},
    {"language":"Armenia","text": "Բարեւ աշխարհ!"},
    {"language":"Basque","text": "Kaixo Mundua!"},
    {"language":"Belarussian","text": "Прывітанне Сусвет!"},
    {"language":"Bengali","text": "ওহে বিশ্ব!"},
    {"language":"Bulgarian","text": "Здравей свят!"},
    {"language":"Catalan","text": "Hola món!"},
    {"language":"Chichewa","text": "Moni Dziko Lapansi!"},
    {"language":"Chinese","text": "你好世界！"},
    {"language":"Croatian","text": "Pozdrav svijete!"},
    {"language":"Czech","text": "Ahoj světe!"},
    {"language":"Danish","text": "Hej Verden!"},
    {"language":"Dutch","text": "Hallo Wereld!"},
    {"language":"English","text": "Hello World!"},
    {"language":"Estonian","text": "Tere maailm!"},
    {"language":"Finnish","text": "Hei maailma!"},
    {"language":"French","text": "Bonjour monde!"},
    {"language":"Frisian","text": "Hallo wrâld!"},
    {"language":"Georgian","text": "გამარჯობა მსოფლიო!"},
    {"language":"German","text": "Hallo Welt!"},
    {"language":"Greek","text": "Γειά σου Κόσμε!"},
    {"language":"Hausa","text": "Sannu Duniya!"},
    {"language":"Hebrew","text": "שלום עולם!"},
    {"language":"Hindi","text": "नमस्ते दुनिया!"},
    {"language":"Hungarian","text": "Helló Világ!"},
    {"language":"Icelandic","text": "Halló heimur!"},
    {"language":"Igbo","text": "Ndewo Ụwa!"},
    {"language":"Indonesian","text": "Halo Dunia!"},
    {"language":"Italian","text": "Ciao mondo!"},
    {"language":"Japanese","text": "こんにちは世界！"},
    {"language":"Kazakh","text": "Сәлем Әлем!"},
    {"language":"Khmer","text": "សួស្តី​ពិភពលោក!"},
    {"language":"Kyrgyz","text": "Салам дүйнө!"},
    {"language":"Lao","text": "ສະ​ບາຍ​ດີ​ຊາວ​ໂລກ!"},
    {"language":"Latvian","text": "Sveika pasaule!"},
    {"language":"Lithuanian","text": "Labas pasauli!"},
    {"language":"Luxemburgish","text": "Moien Welt!"},
    {"language":"Macedonian","text": "Здраво свету!"},
    {"language":"Malay","text": "Hai dunia!"},
    {"language":"Malayalam","text": "ഹലോ വേൾഡ്!"},
    {"language":"Mongolian","text": "Сайн уу дэлхий!"},
    {"language":"Myanmar","text": "မင်္ဂလာပါကမ္ဘာလောက!"},
    {"language":"Nepali","text": "नमस्कार संसार!"},
    {"language":"Norwegian","text": "Hei Verden!"},
    {"language":"Pashto","text": "سلام نړی!"},
    {"language":"Persian","text": "سلام دنیا!"},
    {"language":"Polish","text": "Witaj świecie!"},
    {"language":"Portuguese","text": "Olá Mundo!"},
    {"language":"Punjabi","text": "ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ ਦੁਨਿਆ!"},
    {"language":"Romanian","text": "Salut Lume!"},
    {"language":"Russian","text": "Привет мир!"},
    {"language":"Scots Gaelic","text": "Hàlo a Shaoghail!"},
    {"language":"Serbian","text": "Здраво Свете!"},
    {"language":"Sesotho","text": "Lefatše Lumela!"},
    {"language":"Sinhala","text": "හෙලෝ වර්ල්ඩ්!"},
    {"language":"Slovenian","text": "Pozdravljen svet!"},
    {"language":"Spanish","text": "¡Hola Mundo!"},
    {"language":"Sundanese","text": "Halo Dunya!"},
    {"language":"Swahili","text": "Salamu Dunia!"},
    {"language":"Swedish","text": "Hej världen!"},
    {"language":"Tajik","text": "Салом Ҷаҳон!"},
    {"language":"Thai","text": "สวัสดีชาวโลก!"},
    {"language":"Turkish","text": "Selam Dünya!"},
    {"language":"Ukrainian","text": "Привіт Світ!"},
    {"language":"Uzbek","text": "Salom Dunyo!"},
    {"language":"Vietnamese","text": "Chào thế giới!"},
    {"language":"Welsh","text": "Helo Byd!"},
    {"language":"Xhosa","text": "Molo Lizwe!"},
    {"language":"Yiddish","text": "העלא וועלט!"},
    {"language":"Yoruba","text": "Mo ki O Ile Aiye!"},
    {"language":"Zulu","text": "Sawubona Mhlaba!"}
    ]